settings:
  username: "AlexMnrs"
  commit_msg: "Update profile activity"
  max_lines: 6
  readme_file: "./README.md"
  url_text: "{REPO}"
  date:
    timezone: "Europe/Madrid"
    text: "Last updated: {DATE}"
    format: "dddd, mmmm dS, yyyy, h:MM:ss TT"
  commit_name: "github-actions[bot]"
  commit_email: "41898282+github-actions[bot]@users.noreply.github.com"
  line_prefix: "{NUM}. "
  ignored_repos:
    - AlexMnrs/AlexMnrs
messages:
  comments: "Commented in {REPO}"
  push: "Updated {REPO}"
  issue_opened: "Opened an issue in {REPO}"
  issue_closed: "Closed an issue in {REPO}"
  pr_opened: "Opened a pull request in {REPO}"
  pr_closed: "Closed a pull request in {REPO}"
  pr_merged: "Merged a pull request in {REPO}"
  create_repo: "Created repository {REPO}"
  fork_repo: "Forked {FORK} from {REPO}"
  wiki_create: "Created a wiki page in {REPO}"
  added_member: "Became collaborator on {REPO}"
  changes_approved: "Approved changes in {REPO}"
  changes_requested: "Requested changes in {REPO}"
  new_release: "Released something in {REPO}"
  new_star: "Starred {REPO}"
